name: deploy functions

concurrency:
  group: functions
  cancel-in-progress: false

on:
  push:
    branches:
      - main
    paths:
        - '*.ps1'
        - '*.json'
        - '.github/workflows/deploy.yml'
        - 'startup/*'
        - 'cleanup/*'
        - 'test/*'
  workflow_call:
    inputs:
      no-test:
        required: false
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      no-test:
        required: false
        type: boolean
        default: true
      no-deployment:
        required: false
        type: boolean
        default: false

jobs:
  deploy:
    name: deploy functions
    runs-on: windows-latest
    if: inputs.no-deployment != 'true'
    environment: azure-functions
    permissions:
      id-token: write
    steps:
      - name: checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@8a705c639dc276dfe651189abf11544c5080d384 # v6.2
        with:
          modules-to-cache: |
            Az:12.2.0,
            Az.Accounts:3.0.3,
            Az.ContainerInstance:1.0.3

      - name: copy Azure modules into project
        shell: powershell
        run: |
          ./install.ps1 -ModuleName Az
          ./install.ps1 -ModuleName Az.Accounts
          ./install.ps1 -ModuleName Az.ContainerInstance
      
      - name: Login to Azure
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a # v2.1.1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_426EBB997E104B7BBA2371F9A44EA1FD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CA698282E4EE4B108BA0A7094D216875 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_46D185A5C30E4F0C800067BE25E24C6E }}

      - name: deploy Azure Functions
        uses: Azure/functions-action@fd80521afbba9a2a76a99ba1acc07aff8d733d11 # v1.5.2
        id: fa
        with:
          app-name: ${{ vars.AZ_FUNCTION_APP_NAME }}
          slot-name: 'production'
          package: '.'
  
  test:
    name: invoke webhook
    needs: deploy
    if: inputs.no-test != 'true'
    runs-on:
      - self-hosted
      - azure
      - production
    steps:
      - name: print output
        run: echo "Test successful"

  test-gb:
    name: invoke webhook with specs
    needs: deploy
    if: inputs.no-test != 'true'
    runs-on:
      - self-hosted
      - azure
      - production
      - 2-cores
      - 3-gb
    steps:
      - name: check cpu count
        run: |
          if [ "$(nproc)" -ne 2 ]; then
            echo "Expected 2 CPUs, but found $(nproc)"
            exit 1
          fi

  check:
    name: check final state
    runs-on: ubuntu-latest
    needs:
      - test
      - test-gb
    if: inputs.no-test != 'true'
    steps:
      - name: fail if test runner failed to complete
        if: needs.test.result != 'success'
        run: |
          echo "Test runner was probably cancelled or failed otherwise."
          exit 1
      - name: fail if test runner failed to complete
        if: needs.test-gb.result != 'success'
        run: |
          echo "Test runner was probably cancelled or failed otherwise."
          exit 1
