name: deploy functions

on:
  workflow_call:
    inputs:
      slot:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      slot:
        required: true
        type: string

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
    steps:
      - name: checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      
      - name: Login to Azure
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a # v2.1.1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_426EBB997E104B7BBA2371F9A44EA1FD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CA698282E4EE4B108BA0A7094D216875 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_46D185A5C30E4F0C800067BE25E24C6E }}

      - name: deploy Azure Functions
        uses: Azure/functions-action@v1.5.2
        id: fa
        with:
          app-name: ${{ vars.AZ_FUNCTION_APP_NAME }}
          slot-name: ${{ inputs.slot }}
          package: '.'
